### ISSUE TITLE
Requesting a local quota transform

### ISSUE THREAD

**Issue by uni-pooja-laad** [vectordotdev/vrl#1092]
I am looking for a transform which allows to set a daily limit quota. My source is datadog agent present in k8s cluster and sink is datadog log UI.
I need to send a limited number of logs per day. Example: 200 Millions logs per day. After this it should stop sending logs. 

Please find the link of conversation I had with support team.
https://discord.com/channels/742820443487993987/1298597363585253438/1298597363585253438

**Comment by jszwedko** [comment]
HI @uni-pooja-laad . This would be a feature request for Vector, not VRL. Do you mind opening a request there and filling out all of the details: https://github.com/vectordotdev/vector/issues/new?assignees=&labels=type%3A+feature&projects=&template=feature.yml ? Thanks!
