### ISSUE TITLE
Support for AES-SIV (RFC 5297) to provide Deterministic Encryption/Decryption

### ISSUE THREAD

**Issue by beardface** [vectordotdev/vrl#1100]
## Details
We require Deterministic decryption for our use case, and the ideal algorithm for us is AES-SIV ([RFC 5297](https://datatracker.ietf.org/doc/html/rfc5297)).

More about why AES-SIV -> https://connect2id.com/blog/deterministic-encryption-with-aes-siv

## What needs to update?
The Decrypt lib will need to be updated to support AES-SIV ([here](https://github.com/vectordotdev/vrl/blob/main/src/stdlib/decrypt.rs)).

The following rust library provides an implementation for aes_siv encryption and decryption: https://docs.rs/aes-siv/latest/aes_siv/

**Comment by pront** [comment]
👋 Thank for this request @beardface. Is this something you are willing to contribute a PR for?

**Comment by beardface** [comment]
I'm happy to submit the PR for this one as I'm probably the most motivated to see it supported. :)

**Comment by pront** [comment]
Thank you @beardface! This old PR might be helpful: https://github.com/vectordotdev/vrl/pull/299
