### ISSUE TITLE
feat(stdlib): Function for Converting Character Encodings

### ISSUE THREAD

**Issue by powerumc** [vectordotdev/vrl#1155]
Our system utilizes both legacy systems and the latest Linux distributions. Occasionally, we encounter systems that operate with non-UTF-8 settings. When logs are sent via TCP from these systems, all Korean strings encoded in EUC-KR become corrupted.

To address this issue, I've created a functions.
The function signature is as follows.
```vrl
decode_charset(value, from_charset)
encode_charset(value, to_charset)
```

If this addition is beneficial for the VRL project, I would like to submit a pull request.

**Comment by pront** [comment]
Hi @powerumc, thank you for creating this issue. 

This sound like a generic version to process chars and it could eventually replace functions like the following:
* https://vector.dev/docs/reference/vrl/functions/#encode_base16
* https://vector.dev/docs/reference/vrl/functions/#decode_base16

In general, this sounds like a good idea, and we would be happy to review your PR.

**Comment by powerumc** [comment]
I have created a PR for this issue. #1162 
I would appreciate your review.
