### ISSUE TITLE
Move core VRL documentation out of Vector

### ISSUE THREAD

**Issue by bruceg** [vectordotdev/vrl#1163]
All of the documentation describing VRL actually lives in the Vector repository as part of the [remap reference manual](https://github.com/vectordotdev/vector/tree/master/website/cue/reference/remap). This results in the complication where a change to VRL requires changing both repositories in order to keep the documentation aligned.

It would be helpful for development experience to move the documentation for VRL into this repository such that changes to the core of VRL do not require corresponding changes to Vector other than pulling in the new revision dependency. This will, of course, require building up at least a little infrastructure here to check and possibly format the docs during building and/or CI.

**Comment by pront** [comment]
I agree this is a desirable change! This is probably covered by https://github.com/vectordotdev/vrl/issues/280 but thanks for providing the extra context.

**Comment by bruceg** [comment]
#280 would definitely cover this, but I was going for having this as a first step towards accomplishing that without having to rewrite everything.
