### ISSUE TITLE
Deprecate `to_timestamp` function

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vrl#189]
Deprecate and remove `to_timestamp` function.

Reasoning from https://github.com/vectordotdev/vrl/issues/7#issuecomment-1503761940

> After some discussion on the team, we think having the to_timestamp function have a list of "known formats" does more harm than good since there isn't a clear rule we can apply for what formats qualify to be included. Instead, we'd like to push users to use the parse_timestamp function where they supply the format. Additionally, the to_timestamp function has a parameter, units, for interpreting integer values that we also think is a bit odd and would be better served via a specialized from_unix_timestamp function.

Depends on https://github.com/vectordotdev/vrl/issues/188 being done first.

**Comment by mattnthat** [comment]
@jszwedko Just came across the situation where to_timestamp is failing after attempting to update Vector version. If it has been removed now - What is the recommended approach when you dont know the timestamp format that will be sent in?

We want to accept as wide a range of timestamps as possible and normalise.  to_timestamp was perfect in this regard.

**Comment by mattnthat** [comment]
> 
> In that case, you could use `parse_timestamp` with a set of formats. This is basically what `to_timestamp` did. For example:
> 
> ```
> formats = ["%+c", "some other format"]
> t1 = now() # default
> for_each(formats) -> |_index, format| {
>   t2, err = parse_timestamp(.timestamp, "some other format")
>   if err == null {
>     t1 = t2
>   }
> }
> .timestamp = t1
> ```

This looks great for a work around, Thanks!

> The reason we dropped `to_timestamp` handling of an automatic set of "known formats" is that there wasn't an obvious rule to decide which formats should be considered "known" so we figured it was better to let users decide.
> 
> I think it'd be reasonable to extend `parse_timestamp` to take an array of formats though, to make this a bit easier to do. Would that help in your case? If so, could you open a feature request in this repo?

I think thats a great idea too - No problem ill open a feature request.
