### ISSUE TITLE
Community ID Function

### ISSUE THREAD

**Issue by owen5mith** [vectordotdev/vrl#359]
Hello,

I was looking to implement a `community_id` function that can be used to generate a [community ID](https://github.com/corelight/community-id-spec) for a given network flow. 

[This](https://github.com/vectordotdev/vector/discussions/17984) discussion shows how this can be done in using the current VRL functions, however this is not feature complete and I imagine does not perform as well as if it was implemented as a function.

I have [started work on this](https://github.com/owen5mith/vrl/tree/feature/add-community-id) to check it was viable, if you're open to it being a function in the stdlib then I will look to tidy this up and raise a PR! 😄

**Comment by jszwedko** [comment]
Thanks @owen5mith ! I'm sure we'll have some more low-level feedback to give upon review, but I took a quick look and it seems generally sensible to me if you want to open a PR.
