### ISSUE TITLE
once_cell support by move from anymap to anymap2

### ISSUE THREAD

**Issue by avmartugin** [vectordotdev/vrl#367]
now impossible to use once_cell because Sync or Send does not implemented for AnyMap in anymap crate, but anymap2 does.
need to move for reduce compile overhead each time if use same vrl programm

**Comment by neuronull** [comment]
Hi @avmartugin, thanks for the report. Could you share a little bit more about your scenario, and any errors you are seeing when trying to use `once_cell` ? Thanks

**Comment by jszwedko** [comment]
Closing as stale. Please leave a comment if you pick this back up!
