### ISSUE TITLE
Break out of for_each loop

### ISSUE THREAD

**Issue by mr-karan** [vectordotdev/vrl#391]
I am trying to check if http_slug starts with any of the known paths (it's an array)  then assign that known value to http_slug_known. However I am not able to "stop" processing/enumerating subsequent items in the loop once the if condition has become true. I tried break keyword but it said it's unimplemented yet. Any thoughts on how can I achieve this?

```
# List of known paths
known_paths = [
    "/admin","/forgot", "/reset", "/logout", "/api"
]

http_slug_known = "unknown"
for_each(known_paths) -> |index, path| {
    if starts_with(to_string(http_slug), path) {
        http_slug_known = path
    }
}
```

Current Workaround:

```
found = false
for_each(known_paths) -> |index, path| {
    if !found && starts_with(to_string(http_slug), path) {
        http_slug_known = path
        found = true
    }
}
```

Would be nicer to have a `break` keyword implemented.
```[tasklist]
### Tasks
```

**Comment by pront** [comment]
Hello @mr-karan,

We don't support early termination at the moment.

Please see [here](https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoiIyBMaXN0IG9mIGtub3duIHBhdGhzXG5rbm93bl9wYXRocyA9IFtcbiAgXCIvYWRtaW5cIixcIi9mb3Jnb3RcIiwgXCIvcmVzZXRcIiwgXCIvbG9nb3V0XCIsIFwiL2FwaVwiXG5dXG5odHRwX3NsdWcgPSBcIi9hcGlcIlxuXG5cbmh0dHBfc2x1Z19rbm93biA9IFwidW5rbm93blwiXG4uZmlsdGVyZWQgPSBmaWx0ZXIoa25vd25fcGF0aHMpIC0%2BIHxfaSwgcGF0aHwge1xuICBzdGFydHNfd2l0aCh0b19zdHJpbmcoaHR0cF9zbHVnKSwgcGF0aClcbn1cblxuaWYgbGVuZ3RoKC5maWx0ZXJlZCkgPiAwIHtcbiAgLmh0dHBfc2x1Z19rbm93biA9IC5maWx0ZXJlZFswXVxufVxuIiwiZXZlbnQiOnt9LCJpc19qc29ubCI6ZmFsc2UsImVycm9yIjpudWxsfQ%3D%3D) for a slightly cleaner way to achieve this functionality.
