### ISSUE TITLE
Similar to the parsing function of the Dissect filter plugin in Logstash.

### ISSUE THREAD

**Issue by 41405465** [vectordotdev/vrl#395]
Our applications log in the following format:
[20230813_060934_933][W][TcpClient.cpp::Reconnect:861]Reconnect(id:687 ip:172.26.165.6 port:20882) failed(-17)[TID:118242]

The logstash dissect parsing is implemented as follows：
dissect {
		mapping => {
			"message" => "[%{time}][%{level}][%{file}::%{function}:%{line}]%{content}[TID:%{tid}]"
		}
	}

Does Vector have a parsing function similar to the Logstash Dissect filter plugin's parsing capability?
Dissect differs from Grok in that it does not use regular expressions and is faster. Dissect works well when data is reliably repeated.

**Comment by jszwedko** [comment]
Hi @41405465 . I think the closest we have is the grok parsing functionality. Have you found that that doesn't perform well enough for you? Notably I suspect that VRL's grok parsing is faster than Logstash's due to a more performant regex engine.

**Comment by 41405465** [comment]
How do I handle brackets in parse_grok

**Comment by jszwedko** [comment]
Hi @41405465 ,

Can you share the pattern you tried? I believe you should be able to escape brackets via `\[`. For example, using the `vector vrl` REPL:

```
$ parse_grok!("[hello]", s'\[%{GREEDYDATA:message}\]')
{ "message": "hello" }
```

**Comment by 41405465** [comment]
There is no metadata temporary field in vector, when outputting es append suffix, you want to use the field inside the data, but you don't want to store the field to es, for example, [@metadata][field_name] field in logstash, it won't be outputted to elasticsearch.the following logstash output configuration:

output {
    elasticsearch {
        hosts => ["https://172.26.111:9200"]
        index => "%{**[@metadata][index]**}"
    }
}

**Comment by jszwedko** [comment]
We appear to be going off track of this original issue 😄 Do you mind opening [separate GitHub discussions for your other questions](https://github.com/vectordotdev/vector/discussions)? You can also drop into our Discord server to ask there: chat.vector.dev. That helps others find relevant questions and answers.

Given the original question here appears to have been answered, I'll close this out but I'll keep an eye out for the other questions.
