### ISSUE TITLE
contains all the given substrings in string (contains_all)

### ISSUE THREAD

**Issue by saeed-mcu** [vectordotdev/vrl#417]
I want to determines whether the `string` matches **all** the given `substrings` or not. (all of them MUST contains)
Is it possible to all substrings are checked in a single pass over the target string to achieve good performance advantage over multiple calls to single `contains` function.

if **`contains_all`** function added in String functions of VRL , it can be very useful and applicable for log parsing.

**Comment by pront** [comment]
Hi @saeed-mcu, is the following example what you were thinking?

```
contains_all("The Needle In The Haystack", "Needle", "Haystack") # returns true
```

If yes, that seems reasonable.

**Comment by saeed-mcu** [comment]
Hi @pront  , is the following example return false ?
```
contains_all("The Needle In The Haystack", "Needle", "not_exist") 
```
I expected , all substring exist in the string not one of them.
so I expected above example return false
