### ISSUE TITLE
Allow using strings as json paths

### ISSUE THREAD

**Issue by ayZagen** [vectordotdev/vrl#448]
Currently vrl functions accepts query paths defined in jq like statements. However using strings as json paths is the most common way to interact with jsons

By accepting strings we could write functions like this:

```lua
fields = [".source_type", ".kubernetes.pod_ip"]
for_each(fields) -> |_index, value| {
  del(value)
}
``` 

Strictly related to #25

**Comment by jszwedko** [comment]
Thanks for opening this new issue @ayZagen ! I think it is the same as https://github.com/vectordotdev/vrl/issues/67 . Would you agree?
