### ISSUE TITLE
parse_json gives incorrect results for large integers

### ISSUE THREAD

**Issue by djudd** [vectordotdev/vrl#544]
Example: https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoidmFsdWUgPSBcIjkyMjMzNzIwMzY4NTQ3NzU4MDhcIlxuLnBhcnNlZCwgLmVyciA9IHBhcnNlX2pzb24odmFsdWUpIiwiZXZlbnQiOnt9LCJpc19qc29ubCI6ZmFsc2UsImVycm9yIjpudWxsfQ%3D%3D

input:
```
value = "9223372036854775808"
.parsed, .err = parse_json(value)
```

output:
```
{
	"err": null,
	"parsed": -9223372036854776000
}
```

Some quick experimentation suggests parsing becomes unreliable circa 2^48, but I haven't tested systematically.

(This was found via https://hypothesis.readthedocs.io/en/latest/ tests on my Python code; FWIW I'd suggest using something similar for the parse & encode round-trip in Vector/VRL and might be able to submit that as a contribution if y'all would be interested.)

**Comment by pront** [comment]
Hi @djudd,

Contributions are always welcome. [Here](https://github.com/vectordotdev/vrl/blob/45eb94bd9b427b79f1db4aa9fe0f0bd0ef16b7fe/src/stdlib/parse_json.rs#L10) is the code that parses the JSON bytes. It delegates to `serde_json::from_slice`.

**Comment by StephenWakely** [comment]
This number is greater that is supported by VRL. We should error instead of overflow.

**Comment by pront** [comment]
Agreed, we should go with the least intrusive change i.e. detect that the number cannot be converted to a VRL value and return an error.

Following up on this, @djudd would you like to contribute a fix for this?

**Comment by djudd** [comment]
@pront I'm interested in contributing a fix, but don't want to commit 100% without having given it a shot yet. It'll probably be either next week or not for a while, so if I don't send you a PR by next Friday, please don't block further on me. But I hope to follow up soon.

**Comment by pront** [comment]
Thank you @djudd. If there are no updates by next Friday, I will assign this issue to me.

**Comment by djudd** [comment]
Thank you!
