### ISSUE TITLE
Unable to pass elements of regular expressions list to function parse_regex_all

### ISSUE THREAD

**Issue by spacepatcher** [vectordotdev/vrl#562]
Hi there!
I have a list of regular expressions exported from an external source. I want to use the function `parse_regex_all` with each of them as a parameter. I'm looking for a way to create a code that follows this logic:
```
regex_list = [
r'pattern1',
r'pattern2'
]

for_each(regex_list) -> |_index, _| {
    .http_status = to_string!(.http_status)

    parse_regex_all!(.http_status, regex_list[_index]) # 1. 
    parse_regex_all!(.http_status, get!(regex_list, [_index])) # 2. 
}
```
I expected the function calls in `1.` or `2.` to be executed without any errors, but in fact, errors have occurred accordingly:
```
error[E203]: syntax error
   ┌─ :11:47
   │
11 │     parse_regex_all!(.http_status, regex_list[_index])
   │                                               ^^^^^^
   │                                               │
   │                                               unexpected syntax token: "Identifier"
   │                                               expected one of: "integer literal"
   │
   = see language documentation at https://vrl.dev
   = try your code in the VRL REPL, learn more at https://vrl.dev/examples
```

```
error[E610]: function compilation error: error[E400] unexpected expression type
   ┌─ :13:5
   │
13 │     parse_regex_all!(.http_status, get!(regex_list, [_index]))
   │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   │     │
   │     unexpected expression for argument "pattern"
   │     expected: regex
   │     received: function call
   │
   = learn more about error code 400 at https://errors.vrl.dev/400
   = see language documentation at https://vrl.dev
   = try your code in the VRL REPL, learn more at https://vrl.dev/examples
```

Would you give me any clues on how to implement the desired logic. Cheers!

**Comment by bruceg** [comment]
When using `for_each`, the second value passed to the closure is the value in the array. So, you don't need to use the index for what you want:
```coffee
.http_status = to_string!(.http_status)
for_each(regex_list) -> |_, pattern| {
    parse_regex_all!(.http_status, pattern)
}
```

**Comment by spacepatcher** [comment]
Yes, I also tried it this way, but also without any result. The compiler is very strict and breaks off with a familiar error:
```
error[E610]: function compilation error: error[E400] unexpected expression type
  ┌─ :8:5
  │
8 │     parse_regex_all!(.http_status, pattern)
  │     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  │     │
  │     unexpected expression for argument "pattern"
  │     expected: regex
  │     received: variable call
  │
  = learn more about error code 400 at https://errors.vrl.dev/400
  = see language documentation at https://vrl.dev
  = try your code in the VRL REPL, learn more at https://vrl.dev/examples
```
Here is the playground where I'm testing: https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoicmVnZXhfbGlzdCA9IFtcbiAgICByJ3BhdHRlcm4xJyxcbiAgICByJ3BhdHRlcm4yJ1xuXVxuXG4uaHR0cF9zdGF0dXMgPSB0b19zdHJpbmchKC5odHRwX3N0YXR1cylcbmZvcl9lYWNoKHJlZ2V4X2xpc3QpIC0%2BIHxfLCBwYXR0ZXJufCB7XG4gICAgcGFyc2VfcmVnZXhfYWxsISguaHR0cF9zdGF0dXMsIHBhdHRlcm4pXG59IiwiZXZlbnQiOnsiaHR0cF9zdGF0dXMiOiJwYXR0ZXJuMSJ9LCJpc19qc29ubCI6ZmFsc2UsImVycm9yIjpudWxsfQ%3D%3D

**Comment by pront** [comment]
I would expect [this example](https://playground.vrl.dev/?state=eyJwcm9ncmFtIjoicmVnZXhfbGlzdCA9IFsgXCJwYXR0ZXJuMVwiLCBcInBhdHRlcm4yXCIgXVxuXG5mb3JfZWFjaChyZWdleF9saXN0KSAtPiB8XywgcGF0dGVybnwge1xuICAgIHBhcnNlX3JlZ2V4X2FsbCEodG9fc3RyaW5nISguaHR0cF9zdGF0dXMpLCB0b19yZWdleCEocGF0dGVybikpXG59IiwiZXZlbnQiOnsiaHR0cF9zdGF0dXMiOiJwYXR0ZXJuMSJ9LCJpc19qc29ubCI6ZmFsc2UsImVycm9yIjpudWxsfQ%3D%3D) to work but it doesn't. This is a bug related to closures.

**Comment by pront** [comment]
Discussed this with @fuchsnj: 
Looking at https://vector.dev/docs/reference/vrl/functions/#parse_regex_all, it is actually working as designed. The function is very strict about the regex parameter; *potentially* this was done to discourage dynamically compiling the regex in a loop. We can probably relax this requirement, I will follow up with an enhancement soon.
