### ISSUE TITLE
Using comparison operators with timestamps

### ISSUE THREAD

**Issue by maksimtor** [vectordotdev/vrl#579]
Currently there is no support for comparison operators for timestamps. 

```
ts1 = t'2024-04-04T22:22:22.234142Z'
ts2 = t'2024-04-04T22:22:22.234142Z'

res, err = ts1 < ts2

err
```
-> "can't compare timestamp >= timestamp"

**Comment by jszwedko** [comment]
Duplicate of https://github.com/vectordotdev/vrl/issues/78
