### ISSUE TITLE
Feature request: CDB for enrichment table source

### ISSUE THREAD

**Issue by johnhtodd** [vectordotdev/vrl#660]
We currently use DJB's Constant DataBase (CDB - https://en.wikipedia.org/wiki/Cdb_(software) )   as a source for matching lists in our DNS environment, in the "front-end" systems that see hundreds of thousands or millions of requests per second.  It's quite performant, especially coupled with caching by the local application that is performing the queries.

In the logging stream (DNSTAP) we would also like to use CDB, as this would require no conversion of some of our existing tooling, and would be well-suited for large data set matching and enrichment that would be specific to how we envision using Vector. 

Note: it is fairly trivial to turn CDB into CSV, which might match well with the existing Vector CSV enrichment system. That can mean one of two (or more) options: make the user turn CDB into CSV to avoid the development work, or create an adapter that treats CDB files as CSV and simply converts them at load time. (https://github.com/vectordotdev/vector/blob/13b914781b3c118cbf867609ebab5d5fc6a525dc/rfcs/2021-07-20-8288-csv-enrichment.md) 

I do have a question about CSV functionality, which is why I reference CDB: how are reloads managed? CDB files handle switchout for new data sets exceptionally well, and that is implicit in CDB's model. CSV files as enrichment sources in Vector are less clear - CSV is loaded into memory, but how is that updated without a full restart?

Meta-summary:

Basic desired functionality;
 - Lookup key in CDB, return multi-value results
 - Cache answers (including "no match") for N milliseconds or until CDB file changes (datestamp/size) as checked every N seconds, for performance

There seem to be Rust implementations of CDB, but again I'll not put any suggestions in here as my search-engine based answers in no way should resemble development ideas.  :-)

**Comment by jszwedko** [comment]
> I do have a question about CSV functionality, which is why I reference CDB: how are reloads managed? CDB files handle switchout for new data sets exceptionally well, and that is implicit in CDB's model. CSV files as enrichment sources in Vector are less clear - CSV is loaded into memory, but how is that updated without a full restart?

Reloads can be triggered by issuing a SIGHUP to Vector. https://github.com/vectordotdev/vector/issues/17283 is tracking enhancing `--watch-config` to also look out for changes to referenced enrichment files.

Otherwise it seems like the CSV enrichment support meets your other requirements?

> * Lookup key in CDB, return multi-value results

`get_enrichment_table_records` can return multiple results

> * Cache answers (including "no match") for N milliseconds or until CDB file changes (datestamp/size) as checked every N seconds, for performance

CSVs are loaded into memory and indexes are created based on the queries defined in VRL.

**Comment by johnhtodd** [comment]
Given your comments about CSV, this seems to solve my immediate needs and removes the necessity for this feature request. Very useful to know that `--watch config` looks at enrichment files - maybe that should be more obvious in the docs? 

There is a risk that there end up being no additional enrichment types because there is an expectation that users  convert everything into CSV.  :-)

**Comment by jszwedko** [comment]
> Very useful to know that `--watch config` looks at enrichment files - maybe that should be more obvious in the docs?

It doesn't yet :) https://github.com/vectordotdev/vector/issues/17283 is tracking that as an enhancement request.

**Comment by johnhtodd** [comment]
This ticket can be closed out - you've described a method with CSV that is "good enough" for the moment.  Thanks!  I'll watch the other ticket to see if/when triggering based on file changes happens.

**Comment by jszwedko** [comment]
Thanks @johnhtodd !
