### ISSUE TITLE
join() is fallible, but the doc says it is infallible

### ISSUE THREAD

**Issue by julienkosinski** [vectordotdev/vrl#711]
Hello!

I am unsure on which project vector.dev VRL doc is located. Feel free to close this issue and recreate it where needed.
The doc says that join() function is infallible, but as the examples states it well, it should display that it is fallible.

Doc: https://vector.dev/docs/reference/vrl/functions/#join

Thank you! :)

**Comment by jszwedko** [comment]
Hi @julienkosinski ! This is admittedly a common form of confusion, but `infallible` functions are only infallible if the argument types are known to be valid. This is described here: https://vector.dev/docs/reference/vrl/expressions/#function-call-characteristics

I'll close this out but let me know if you have more questions!
