### ISSUE TITLE
Add "dns_lookup" function

### ISSUE THREAD

**Issue by johnhtodd** [vectordotdev/vrl#720]
We have a need to perform lookups on DNS results delivered to us via the DNSTAP source, to determine (as an example) if an error is transient, or is related to a specific geography of resolvers that may be malfunctioning. Also, some DNS requests may yield lookup data in some cases, where a TXT or other result can be used to enrich the logging message as it moves through Vector, or where NS records may be used to enrich data such as "What authoritative nameserver cluster provided these answers?"

We would therefore like to request this as a VRL feature to be added to Vector that allows DNS requests to be emitted from Vector, and the result of those queries to be handed back in some easily parseable way.   The good news is that there already exists a DNSTAP structure, and so this would require grafting an existing Rust-based resolver library to produce results that could be fed to the DNSTAP parser as replies.

There are caveats here, and that is understood. These may be slow processes - the DNS is not easily predicted for response times. Local caches should be used, possibly on the same server as Vector is operating, in order to accelerate results. Timeouts and retries for failures should probably be kept low as a best-practice - "fail fast."  Simply because this may be slow is not sufficient to not perform the lookups - we will probably execute these on a sampled set of events in order to tune an adequate response rate to the stream of total inbound events we need to parse.

This would specifically not allow queries for QTYPEs of AXFR, IXFR, or ANY as they are too complex to easily render and are difficult to imagine in a Vector use case.

Ideally these fields would be used:

 - qname (mandatory)
 - QTYPE (mandatory)
 - namesever destination (optional - if not specified, system resolver will be used)
 - options (optional)
 - class (optional, default IN)

The reply from the resolver code would be handed back as a DNSTAP message structure.

Example:

`.myDnsResult = dns_lookup!("www.example.com", "9.9.9.9", "A", ["timeout=1", "tries=1", "nodnssec", "nsid"])
`

Errors in the DNS lookup should not produce errors within Vector, unless they are invalid command options which cannot be parsed. NXDOMAIN, SERVFAIl, etc. are all legitimate responses from the resolver stack, and should be represented in the DNSTAP message and not raise an error in Vector.  Only if the syntax of the command is incorrect should the lookup fail with an error outcome that is fallible, or if there is a timeout in the response (should this be a fixed number like 5 seconds?) or if there is some problem executing the command like no sockets available or no route to IP address for the recursive resolver.

This option list cribbed from recent Debian "dig" options that seem relevant and which are not redundant:

Options:
```
   [no]aaflag         (Set AA flag in query ([no]aaflag))
   [no]adflag         (Set AD flag in query (default on))
   [no]badcookie      (Retry BADCOOKIE responses)
   bufsize[=###]      (Set EDNS0 Max UDP packet size)
   [no]cdflag         (Set checking disabled flag in query)
   [no]cookie         (Add a COOKIE option to the request)
   [no]dns64prefix    (Get the DNS64 prefixes from ipv4only.arpa)
   [no]dnssec         (Request DNSSEC records)
   [no]edns[=###]     (Set EDNS version) [0]
   ednsflags=###      (Set EDNS flag bits)
   [no]ednsnegotiation (Set EDNS version negotiation)
   ednsopt=###[:value] (Send specified EDNS option)
   noednsopt          (Clear list of ednsopt options)
   [no]expire         (Request time to expire)
   [no]fail           (Don't try next server on SERVFAIL)
   [no]header-only    (Send query without a question section)
   [no]ignore         (Don't revert to TCP for TC responses.)
   ndots=###          (Set search NDOTS value)
   [no]nsid           (Request Name Server ID)
   [no]nssearch       (Search all authoritative nameservers)
   [no]opcode=###     (Set the opcode of the request)
   padding=###        (Set padding block size [0])
   qid=###            (Specify the query ID to use when sending queries)
   [no]raflag         (Set RA flag in query ([no]raflag))
   [no]recurse        (Recursive mode ([no]rdflag))
   retry=###          (Set number of UDP retries) [2]
   subnet=addr        (Set edns-client-subnet option)
   [no]tcflag         (Set TC flag in query)
   [no]tcp            (TCP mode)
   timeout=###        (Set query timeout) [5]
   tries=###          (Set number of UDP attempts) [3]
   [no]zflag          (Set Z flag in query)


```

**Comment by jszwedko** [comment]
Thanks for this idea @johnhtodd ! Historically we've shied away from having VRL programs make network calls since it can have a large impact on throughput (see https://github.com/vectordotdev/vrl/blob/main/DESIGN.md#language-limits). There are also a lot of nuances to consider, which you've also noted, like what to do about retries, failures, caching, etc. That's not to say we wouldn't consider adding functions with these characteristics to VRL, but I think we'll want to tread carefully. As a compromise maybe we could add this function but not expose it by default (hide it behind an "experimental" VRL flag).

As a workaround, you could consider using a `lua` transform in Vector which, while it introduces overhead, gives you access to a full language capable of doing pretty much whatever you want. In the future I'd also love to see us bring back the `wasm` transform to execute user-defined code in a more performant manner.

**Comment by johnhtodd** [comment]
Thanks for the comments @jszwedko !  Yes, I'm aware of the risks with network connections from within the confines of a highly-optimized loop.  However, I also accept that risk because the outreach is going to be mandatory for our needs for enrichment of objects.  I put some comments in this ticket which talks more about DNS lookups - I'm not the first person to need this, it appears from the conversations: https://github.com/vectordotdev/vector/issues/4517   I really like the idea floated in that ticket about Vector-specific caching. For a limited set of replies, that would indeed speed things up, and I suspect most use cases will have a fairly finite set of records that get looked up, even if they are in the thousands or tens of thousands. I didn't know that "reverse_dns" existed, either.  Is there a secret list of the undocumented features somewhere? It doesn't solve our issue, but it's an interesting demonstration that this has at least surfaced before for other needs. 

I'll look at how to do this with Lua, but that's... ugh. And it won't present the data in a format that I can just consume and figure out using existing Vector concepts, like a DNSTAP-formatted message would - I will have to parse the output of something like (ugh again) dig or kdig or (ugh a third time) write a tiny bit of code to produce correctly-structured output.

**Comment by johnhtodd** [comment]
Or... ugh yet again... I could make a lua call to curl to connect to the JSON output of this code: https://github.com/m13253/dns-over-https?tab=readme-ov-file   ... but timeouts, options, etc. are entirely absent from that model and it will almost certainly back up the pipeline.

**Comment by pront** [comment]
I think this goes hand in hand with a proper runtime state + caching proposal. We could benefit in others areas as well from this.
