### ISSUE TITLE
Argument named to_lowercase has unintuitive behavior

### ISSUE THREAD

**Issue by andrewthad** [vectordotdev/vrl#802]
I spent a while tracking down why something wasn't working, and the problem was that I had misunderstood the `convert_to_string` function:

```
pub(crate) fn convert_to_string(value: Value, to_lowercase: bool) -> Result<String, ValueError> {
    let string = value.try_bytes_utf8_lossy()?;
    Ok(match to_lowercase {
        true => string.to_string(),
        false => string.to_lowercase(),
    })
}
```

The argument `to_lowercase` can be used to convert the string to be converted to lowercase, but the caller must set it to `false` to do this! I suggest renaming this argument to `is_case_sensitive` or something like that to prevent confusion about its meaning.

**Comment by jszwedko** [comment]
Thanks @andrewthad . That is confusing. I'd suggest we keep the parameter name the same, but invert the match, and update the callers to pass in the opposite of what they are currently passing in.
