### ISSUE TITLE
Add `unflatten` function

### ISSUE THREAD

**Issue by jszwedko** [vectordotdev/vrl#81]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Current Vector Version

```
vector 0.19.1 (x86_64-apple-darwin 3cf70cf 2022-01-25)
```

### Use-cases

We have a `flatten` function that flattens objects by joining together nested keys with `.`. It'd be useful to have a way to reverse this. This could also be useful for sources of data that use `.`s in keys.

See https://github.com/vectordotdev/vector/discussions/11062

### Attempted Solutions

This `lua` transform works:

```toml
[transforms.nest]
type = "lua"
inputs = ["stdin"]
version = "2"
source = '''
function build_array(...)
  local arr = {}
  for v in ... do
    arr[#arr + 1] = v
  end
  return arr
end

function process(event, emit)
  for key, value in pairs(event.log) do
    event.log[key] = value

    parts = build_array(string.gmatch(key, "[^\\.]+"))

    -- key has a dot in it, break it apart to create nested table
    if #parts > 1 then
      event.log[key] = nil

      to_update = event.log
      for i = 1, #parts - 1 do
        if to_update[parts[i]] == nil then
          to_update[parts[i]] = {}
        end
        to_update = to_update[parts[i]]
      end
      to_update[parts[#parts]] = value
    end
  end
  emit(event)
end
'''
hooks.process = "process"
```

### Proposal

We add a `unflatten` function to VRL that does the opposite of `flatten`.

**Comment by fpytloun** [comment]
Simple VRL implementation of unflatten using `.` as separator:

```
for_each(.) -> |key, value| {
  key_split = split(key, ".")
  if length(key_split) > 1 {
    . = set!(., path: key_split, data: value)
    . = remove!(., path: [key])
  }
}
```
