### ISSUE TITLE
Community ID is incorrect for ICMP

### ISSUE THREAD

**Issue by DylanRJohnston** [vectordotdev/vrl#891]
I've let the upstream library know of the problem, but I thought you guys might also be interested in the problem. https://github.com/traceflight/rs-community-id/issues/3

**Comment by jszwedko** [comment]
Thanks! We'll track the upstream issue.

**Comment by DylanRJohnston** [comment]
I've got a pull request up to fix the issue https://github.com/traceflight/rs-community-id/pull/4

**Comment by DylanRJohnston** [comment]
I also think the documentation needs to be updated on the `community_id` function to point out that `source_port` and `destination_port` for `ICMP` is actually overloaded and ICMP type and ICMP code respectively. This was very confusing when I was first investigating the issue, especially as Elastic Search separates those arguments. Perhaps it would be wise to do the same as overloading the meaning of named arguments is very confusing.

**Comment by DylanRJohnston** [comment]
Found further problems with the handling of ICMP with IPv6 addresses https://github.com/traceflight/rs-community-id/issues/5

**Comment by jszwedko** [comment]
Nice, thanks @DylanRJohnston, good finds.

The overloading of port to be ICMP type and code is a bit confusing. I see that, for example, [the Go library](https://pkg.go.dev/github.com/satta/gommunityid#section-documentation) has separate functions per level 4 protocol and also ICMP. We could do something similar. Notably [the C implementation](https://github.com/corelight/c-community-id/blob/master/communityid.c#L179-L185) seems to also overload like we are. I'll open a PR to update the docs for now at least.

**Comment by jszwedko** [comment]
Docs update: https://github.com/vectordotdev/vector/pull/20677

**Comment by traceflight** [comment]
Thanks @DylanRJohnston. I have released a new version of rs-community-id. Feel free to mention me if any issue found~
