### ISSUE TITLE
Convert object to string.

### ISSUE THREAD

**Issue by evanzhang87** [vectordotdev/vrl#950]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

```
{
    "key_l1": "value",
    "key_l1_2": {
        "key_l2": "hello"
    },
    "key_l1_3": {
        "key_l2_2": {
            "key_l3": "hello"
        }
    }
}
```
For multi level json message, I want to `flatten` only just one level, like this:
```
{
    "key_l1": "value",
    "key_l1_2_key_l2": "hello",
    "key_l1_3_key_l2_2": {
         "key_l3": "hello"
    }
}
```
But I think it's more common to convert object to string.

**Comment by evanzhang87** [comment]
Sorry, I want to make a `json string` value, like `{\"key_l3\": \"hello\"}"`, my value is from a multi level json, so I want to `flatten` one level, but it's not so important, because I can use `vrl` : `.keyl1_l2 = .keyl1.l2`。

**Comment by jszwedko** [comment]
Ah, you can turn an object into a JSON string via https://vector.dev/docs/reference/vrl/functions/#encode_json . Is that what you mean?

**Comment by evanzhang87** [comment]
Wow, it works!  thx~
