### ISSUE TITLE
include camelCase in VRL

### ISSUE THREAD

**Issue by leshow** [vectordotdev/vrl#970]
### A note for the community

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use Cases

a common operation is translating keys between snake_case, camelCase, PascalCase, etc. It would be nice to have this supported directly in VRL along with existing `downcase` and `upcase` functions.

### Attempted Solutions

Some manual VRL script is the only other option

### Proposal

Have not looked into the implementation details but I would propose adding those API functions which do the transformation. I'm happy to attempt a PR if someone can point me to a good place to start.

### Version

0.40.0

**Comment by jszwedko** [comment]
Agreed, these additional functions would be useful. Thanks for proposing @leshow . If you or anyone else wants to take a shot at contributing them you can see the existing `upcase` and `downcase` function implementations for reference (`grep` for `upcase` to see everywhere you need to update to add a new function).

**Comment by leshow** [comment]
I was thinking about the best API for these functions and I think accepting an array of strings might be an easy way to do it? This way you'd have like
```
camelcase(split(s, "_"))
```
Of course, if you had PascalCase as your input, it becomes a little harder to write the `split` function.

The problem otherwise is that each of these needs to figure out what the casing of the input is. The other option would be a parameter indicating what the input casing format is

```
camelcase(s, "snake_case")
```
for a conversion from snake_case -> camelCase for instance

do you have a preference for which API you prefer? I think maybe the second is more usable?

**Comment by jszwedko** [comment]
Good questions, I was thinking this would be simpler than it seems. There is definitely some nuance here.

As some prior art, and potentially useful in the implementation of these VRL functions, I found this Rust crate that does conversions: https://docs.rs/convert_case/latest/convert_case/. Using that as inspiration, I'd suggest:

```
camelcase(value : <string>, [original_case: [snake, camel, sentence, etc.])
```

Where the `original_case` field would be optional. If it isn't specified, the implementation its best and then, if the case is known, it could be specified for a more accurate conversion. What do you think?

**Comment by jszwedko** [comment]
Maybe `value` could also be a `[string]` in case it has already been tokenized. It should be able to define the function to take both argument types. See https://github.com/vectordotdev/vrl/blob/16889935bf08268547dd494054dc906705a1dfc7/src/stdlib/redact.rs#L33 for an example.

**Comment by leshow** [comment]
Sounds good, I'll take a look at the crate

**Comment by leshow** [comment]
Unless I'm mistaken, I don't think there's an example here of taking an argument that is a bounded set of possible values. Like, can the type system express `"snake_case" | "camelCase" | ...` somehow? In the absence of that my second parameter is more permissive and errors are pushed to runtime:
```
            Parameter {
                keyword: "original_case",
                kind: kind::BYTES,
                required: false,
            },
```

**Comment by jszwedko** [comment]
> Unless I'm mistaken, I don't think there's an example here of taking an argument that is a bounded set of possible values. Like, can the type system express `"snake_case" | "camelCase" | ...` somehow? In the absence of that my second parameter is more permissive and errors are pushed to runtime:
> 
> ```
>             Parameter {
>                 keyword: "original_case",
>                 kind: kind::BYTES,
>                 required: false,
>             },
> ```

You can see https://github.com/vectordotdev/vrl/blob/16889935bf08268547dd494054dc906705a1dfc7/src/stdlib/parse_nginx_log.rs#L69-L72 for an example of restricting the values at "compile" time.
