### ISSUE TITLE
Support contains_any function?

### ISSUE THREAD

**Issue by suikammd** [vectordotdev/vrl#996]
Recently I wants to use vrl express `or` when do string contains, may add a contains_any function is batter than `contains(xx) || contains(yy) || contains(zz)`. I can help make it.

**Comment by jorgehermo9** [comment]
I think that could be easily done with regexes and the `match` function

https://vector.dev/docs/reference/vrl/functions/#match


For example `match(string,r'xx|yy|zz')`

I don't know if it would be worth to have an specific function to do that 🤔

**Comment by jszwedko** [comment]
I agree. I think using `match` is a good enough approach that we probably don't need an additional function. Would that work for you @suikammd ?

**Comment by suikammd** [comment]
> I think that could be easily done with regexes and the `match` function
> 
> https://vector.dev/docs/reference/vrl/functions/#match
> 
> For example `match(string,r'xx|yy|zz')`
> 
> I don't know if it would be worth to have an specific function to do that 🤔

Get! That's totally work for me.
